"""
email_sender.py — send the daily podcast script as a formatted HTML email.

Sends to the dedicated project Gmail account immediately after synthesis,
providing a searchable text archive of every episode independent of the audio.

Authentication: Gmail app password (not OAuth). Generate one at:
  myaccount.google.com → Security → 2-Step Verification → App passwords

Required env vars (in .env / GitHub Secrets):
  GMAIL_ADDRESS       — the dedicated Gmail account (sender and recipient)
  GMAIL_APP_PASSWORD  — 16-character app password from Google account settings

Degrades gracefully: if credentials are not set, logs a warning and skips.
"""

import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD

logger = logging.getLogger(__name__)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def send_daily_brief(script: str, word_count: int, date_str: str = None) -> bool:
    """Send the podcast script as a formatted HTML email.

    Args:
        script:      Full podcast script text from synthesizer
        word_count:  Word count (for subject line)
        date_str:    Date string for subject (defaults to today)

    Returns:
        True if sent successfully, False otherwise.
    """
    if not GMAIL_ADDRESS or not GMAIL_APP_PASSWORD:
        logger.warning("Email: GMAIL_ADDRESS or GMAIL_APP_PASSWORD not set — skipping")
        return False

    if not date_str:
        date_str = datetime.today().strftime("%Y-%m-%d")

    subject = f"Morning Brief — {date_str} ({word_count} words)"
    html_body = _format_html(script, date_str, word_count)
    plain_body = script  # fallback for email clients that don't render HTML

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = GMAIL_ADDRESS
        msg["To"] = GMAIL_ADDRESS  # send to self — dedicated archive account

        msg.attach(MIMEText(plain_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, GMAIL_ADDRESS, msg.as_string())

        logger.info(f"Email: brief sent to {GMAIL_ADDRESS} ({word_count} words)")
        return True

    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Email: authentication failed — check GMAIL_APP_PASSWORD. "
            "Must be an app password (16 chars), not your regular Gmail password. "
            "Generate at: myaccount.google.com → Security → App passwords"
        )
        return False

    except Exception as e:
        logger.error(f"Email: send failed — {e}")
        return False


def _format_html(script: str, date_str: str, word_count: int) -> str:
    """Wrap the script in clean HTML for readable email rendering."""
    # Convert paragraph breaks to HTML
    paragraphs = script.strip().split("\n\n")
    html_paragraphs = "\n".join(f"<p>{p.strip()}</p>" for p in paragraphs if p.strip())

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{
    font-family: Georgia, serif;
    font-size: 16px;
    line-height: 1.7;
    color: #1a1a1a;
    max-width: 760px;
    margin: 40px auto;
    padding: 0 20px;
  }}
  .header {{
    border-bottom: 2px solid #1a1a1a;
    padding-bottom: 12px;
    margin-bottom: 28px;
  }}
  .header h1 {{
    font-size: 20px;
    font-weight: bold;
    margin: 0 0 4px 0;
  }}
  .header .meta {{
    font-size: 13px;
    color: #666;
  }}
  p {{
    margin: 0 0 18px 0;
  }}
  .footer {{
    border-top: 1px solid #ccc;
    margin-top: 36px;
    padding-top: 12px;
    font-size: 12px;
    color: #999;
  }}
</style>
</head>
<body>
  <div class="header">
    <h1>Morning Audio Brief</h1>
    <div class="meta">{date_str} &nbsp;·&nbsp; {word_count} words</div>
  </div>

  {html_paragraphs}

  <div class="footer">
    Generated by Morning Audio Brief pipeline · {date_str}
  </div>
</body>
</html>"""
